# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/apiops-cli/main/schemas/v1/override-config.schema.json

namedValues:
  - name: environment
    properties:
      displayName: environment
      value: https://www.bing.com
  - name: demo
    properties:
      displayName: demo
      value: demo message new again again
  - name: TimeNow
    properties:
      displayName: TimeNow
      value: "@(DateTime2.Now.ToString())"
  - name: testSecret
    properties:
      displayName: testSecret
      value: "{#[TEST_SECRET_VALUE]#}"
  - name: signingKey
    properties:
      displayName: signingKey
      keyVault:
        secretIdentifier: https://red-scus-apimdemo-kv-prd.vault.azure.net/secrets/APIM-signing-key
  - name: 639121f85ddd1701d02ea23f
    properties:
      displayName: Logger-Credentials--639121f85ddd1701d02ea240
      value: "{#[APP_INSIGHTS_LOGGER_KEY]#}"
  - name: allowed-ip-address
    properties:
      displayName: allowed-ip-address
      value: "{#[ALLOWED_IP_ADDRESS]#}"
loggers:
    - name: red-scus-apim-ai-dev
      properties:
        loggerType: applicationInsights
        description: App insights logger info
        resourceId: "/subscriptions/{#[AZURE_SUBSCRIPTION_ID]#}/resourceGroups/{#[RESOURCE_GROUP_NAME]#}/providers/microsoft.insights/components/red-scus-apim-appinsights-prd"
        credentials:
          instrumentationKey: "{{Logger-Credentials--639121f85ddd1701d02ea240}}"
        isBuffered: true
diagnostics:
    - name: applicationinsights
      properties:
        verbosity: Error
        loggerId: "/subscriptions/{#[AZURE_SUBSCRIPTION_ID]#}/resourceGroups/{#[RESOURCE_GROUP_NAME]#}/providers/Microsoft.ApiManagement/service/{#[APIM_INSTANCE_NAME]#}/loggers/red-scus-apim-ai-dev"
subscriptions:
  - name: "66ce4b511f9b910053070002"
    properties:
      displayName: "Unlimited Set By APIOps"
      scope: "/subscriptions/{#[AZURE_SUBSCRIPTION_ID]#}/resourceGroups/{#[RESOURCE_GROUP_NAME]#}/providers/Microsoft.ApiManagement/service/{#[APIM_INSTANCE_NAME]#}/products/unlimited"
      ownerId: "/subscriptions/{#[AZURE_SUBSCRIPTION_ID]#}/resourceGroups/{#[RESOURCE_GROUP_NAME]#}/providers/Microsoft.ApiManagement/service/{#[APIM_INSTANCE_NAME]#}/users/1"
      primaryKey: "{#[UNLIMITED_SUBSCRIPTION_PRIMARY_KEY]#}"
      secondaryKey: "{#[UNLIMITED_SUBSCRIPTION_SECONDARY_KEY]#}"
apis:
  - name: "basic-calculator;rev=1"
    properties: {}
    diagnostics:
      - name: applicationinsights
        properties:
          verbosity: Error
          loggerId: "/subscriptions/{#[AZURE_SUBSCRIPTION_ID]#}/resourceGroups/{#[RESOURCE_GROUP_NAME]#}/providers/Microsoft.ApiManagement/service/{#[APIM_INSTANCE_NAME]#}/loggers/red-scus-apim-ai-dev"
  - name: "test"
    properties:
      apiVersionSetId: "/subscriptions/{#[AZURE_SUBSCRIPTION_ID]#}/resourceGroups/{#[RESOURCE_GROUP_NAME]#}/providers/Microsoft.ApiManagement/service/{#[APIM_INSTANCE_NAME]#}/apiVersionSets/6398be47eb8d2b6560dd061a"
  - name: "starwars-v1"
    properties:
      apiVersionSetId: "/subscriptions/{#[AZURE_SUBSCRIPTION_ID]#}/resourceGroups/{#[RESOURCE_GROUP_NAME]#}/providers/Microsoft.ApiManagement/service/{#[APIM_INSTANCE_NAME]#}/apiVersionSets/6398be47eb8d2b6560dd061a"
  - name: "testopenai"
    properties: {}
    diagnostics:
      - name: azuremonitor
        properties:
          largeLanguageModel:
            logs: "enabled"
            requests:
              messages: "all"
              maxSizeInBytes: 32768
            responses:
              messages: "all"
              maxSizeInBytes: 32768
